name: Compile TypeScript

on:
  push:
    branches:
      - main
    paths:
      - 'docs/ts/**'

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install TypeScript
        run: npm install -g typescript

      - name: Compile TypeScript
        run: tsc

      - name: Commit and push changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore: Auto-compile TypeScript to JS"
          file_pattern: "docs/js/*.js"
